# Generated by Django 5.2.7 on 2025-11-06 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('Adult_ticket_price', models.IntegerField(blank=True, null=True)),
                ('Child_ticket_price', models.IntegerField(blank=True, null=True)),
                ('Senior_ticket_price', models.IntegerField(blank=True, null=True)),
                ('Student_ticket_price', models.IntegerField(blank=True, null=True)),
                ('weekend_surcharge', models.IntegerField(blank=True, null=True)),
                ('holiday_surcharge', models.IntegerField(blank=True, null=True)),
                ('weekday_discount', models.IntegerField(blank=True, null=True)),
                ('matinee_discount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='movie_covers/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(blank=True, db_column='rating', null=True),
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_time', models.DateTimeField()),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinema_showtimes', to='viewer.cinema')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='viewer.movie')),
            ],
        ),
    ]
