# Generated by Django 5.2.7 on 2025-11-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_cinema_movie_bio_movie_profile_picture_movie_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='Year',
            new_name='year',
        ),
        migrations.AddField(
            model_name='cinema',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
