# Generated by Django 5.2.7 on 2025-10-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, db_column='title', max_length=100, null=True)),
                ('director', models.CharField(blank=True, db_column='director', max_length=100, null=True)),
                ('Year', models.IntegerField(blank=True, db_column='year', null=True)),
                ('cinema_price', models.IntegerField(blank=True, db_column='cinema_price', null=True)),
                ('genre', models.CharField(blank=True, db_column='genre', max_length=100, null=True)),
            ],
        ),
    ]
