# Generated by Django 5.2.7 on 2025-10-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_remove_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre_movie',
            field=models.CharField(blank=True, db_column='genre_movie', max_length=50, null=True),
        ),
    ]
