# Generated by Django 5.2.7 on 2025-11-04 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(blank=True, db_column='rating', null=True),
        ),
    ]
