# Generated by Django 5.2.7 on 2025-11-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_movie_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='name', max_length=100, null=True)),
                ('location', models.CharField(blank=True, db_column='location', max_length=100, null=True)),
                ('capacity', models.IntegerField(blank=True, db_column='capacity', null=True)),
                ('Adult_ticket_price', models.IntegerField(blank=True, db_column='adult_ticket_price', null=True)),
                ('Child_ticket_price', models.IntegerField(blank=True, db_column='child_ticket_price', null=True)),
                ('Senior_ticket_price', models.IntegerField(blank=True, db_column='senior_ticket_price', null=True)),
                ('Student_ticket_price', models.IntegerField(blank=True, db_column='student_ticket_price', null=True)),
                ('weekend_surcharge', models.IntegerField(blank=True, db_column='weekend_surcharge', null=True)),
                ('holiday_surcharge', models.IntegerField(blank=True, db_column='holiday_surcharge', null=True)),
                ('weekday_discount', models.IntegerField(blank=True, db_column='weekday_discount', null=True)),
                ('matinee_discount', models.IntegerField(blank=True, db_column='matinee_discount', null=True)),
            ],
        ),
    ]
