# Generated by Django 5.2.7 on 2025-11-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_remove_movie_cinema_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='movie_covers/'),
        ),
    ]
