# Generated by Django 5.2.7 on 2025-11-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0010_alter_cinema_adult_ticket_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema',
            name='holiday_surcharge',
        ),
        migrations.RemoveField(
            model_name='cinema',
            name='matinee_discount',
        ),
        migrations.RemoveField(
            model_name='cinema',
            name='weekday_discount',
        ),
        migrations.AlterField(
            model_name='cinema',
            name='Adult_ticket_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='Child_ticket_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='Senior_ticket_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='Student_ticket_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='weekend_surcharge',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
