# Generated by Django 5.2.7 on 2025-11-05 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0011_remove_cinema_holiday_surcharge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='cinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinema_showtimes', to='viewer.cinema'),
        ),
    ]
